lib/pfu_web/router.ex
defmodule PfuWeb.Router do
  use PfuWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PfuWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PfuWeb.Auth, repo: Pfu.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PfuWeb do
    pipe_through :browser

    live "/", PageLive, :index
    get  "/hello/:name", HelloController, :world
    get "/logout", LogoutController, :index
    #get "/users", UserController, :index
    #get "/users/:id", UserController, :show
    resources "/users", UserController, only: [:index, :show, :new, :create, :delete, :edit, :update]
    resources "/tipos", TipoController, only: [:index, :show, :new, :create, :delete, :edit, :update]
    resources "/sessions", SessionController, only: [:new, :create, :delete]

    live "/posts", PostLive.Index, :index
    live "/posts/new", PostLive.Index, :new
    live "/posts/:id/edit", PostLive.Index, :edit

    live "/posts/:id", PostLive.Show, :show
    live "/posts/:id/show/edit", PostLive.Show, :edit

  end

  # Other scopes may use custom stacks.
  # scope "/api", PfuWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: PfuWeb.Telemetry
    end
  end
end

lib/pfu_web/views/layout_view.ex
defmodule PfuWeb.LayoutView do
  use PfuWeb, :view
end

lib/pfu_web/templates/layout/app.html.eex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/pfu_web/templates/layout/live.html.leex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/pfu_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Pfu", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <div class="container">
            <a href="/"><i class="fa fa-home">HOME | </i></a>
            <a href="/users"><i class="fa fa-users">USUARIOS | </i></a>
            <a href="/tipos"><i class="fa fa-users">TIPOS | </i></a>
            <a href="/posts"><i class="fa fa-users">POSTAGENS | </i></a>
            <i class="fa fa-registered"> <%= link "Criar Tipos | ", to: Routes.tipo_path(@conn, :new) %></i>
            <!--
            <a href="/posts"><i class="fa fa-comments"> Timeline</i></a>
            -->
            <%= if !@current_user do %>
              <!--
              <a href="/manage/profile"><i class="fa fa-id-card"> Profile</i></a>
              <a href="/sessions/new"><i class="fa fa-key"> Enter</i></a>
              -->
              <i class="fa fa-registered"> <%= link "Registrar | ", to: Routes.user_path(@conn, :new) %></i>
              <i class="fa fa-registered"> <%= link "LOGIN | ", to: Routes.session_path(@conn, :new) %></i>
            <% else %>
              <%= link "NOVO | ", to: PfuWeb.Router.Helpers.user_path(@conn, :new) %>
              <%= Phoenix.HTML.Link.link("SAIR ("<>@current_user.username<>") ", to: "/logout") %>
              <!--
              <a href="/manage/profile"><i class="fa fa-id-card"> <%= @current_user.username %></i></a>
              <i class="fa fa-power-off"> <%=# link "SAIR ", to: Routes.session_path(@conn, :delete, @current_user), method: "delete" %></i>
              -->
            <% end %>
        <!-- <a href="/" class="phx-logo"> <img src="<%= Routes.static_path(@conn, "/images/logo.png") %>" alt="Home" width="58" height="64" /> </a> -->
      </div>
    </header>
    <%= @inner_content %>
  </body>
</html>